//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kartonagen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Umzugsfortschritt
    {
        public int idUmzugsfortschritt { get; set; }
        public Nullable<int> Besichtigung { get; set; }
        public Nullable<System.DateTime> datBesichtigung { get; set; }
        public Nullable<int> KVAMail { get; set; }
        public Nullable<System.DateTime> datKVAMail { get; set; }
        public Nullable<int> KVAPost { get; set; }
        public Nullable<System.DateTime> datKVAPost { get; set; }
        public Nullable<int> BuchungTel { get; set; }
        public Nullable<System.DateTime> datBuchungTel { get; set; }
        public Nullable<int> BuchungSchrift { get; set; }
        public Nullable<System.DateTime> datBuchungSchrift { get; set; }
        public Nullable<int> BuchungFin { get; set; }
        public Nullable<System.DateTime> datBuchungFin { get; set; }
        public Nullable<int> Bestaetigung { get; set; }
        public Nullable<System.DateTime> datBestaetigung { get; set; }
        public Nullable<int> LKW { get; set; }
        public Nullable<System.DateTime> datLKW { get; set; }
        public Nullable<int> HVZWunder { get; set; }
        public Nullable<System.DateTime> datHVZWunder { get; set; }
        public Nullable<int> HVZAntrag { get; set; }
        public Nullable<System.DateTime> datHVZAntrag { get; set; }
        public Nullable<int> KuecheTermin { get; set; }
        public Nullable<System.DateTime> datKuecheTermin { get; set; }
        public Nullable<int> KVAKorrektur { get; set; }
        public Nullable<System.DateTime> datKVAKorrektur { get; set; }
        public string Bemerkung { get; set; }
        public int Umzuege_idUmzuege { get; set; }
        public Nullable<int> Schaden { get; set; }
        public Nullable<int> HVZKosten { get; set; }
        public Nullable<int> Sonderkosten { get; set; }
        public Nullable<int> SummeKosten { get; set; }
        public Nullable<int> Erinnerung { get; set; }
        public Nullable<System.DateTime> datErinnerung { get; set; }
        public sbyte abgeschlossen { get; set; }
    }
}
