//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kartonagen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Umzuege
    {
        public Umzuege()
        {
            this.Transaktionens = new HashSet<Transaktionen>();
        }
    
        public int idUmzuege { get; set; }
        public int Kunden_idKunden { get; set; }
        public Nullable<System.DateTime> datBesichtigung { get; set; }
        public Nullable<System.DateTime> datUmzug { get; set; }
        public Nullable<System.DateTime> datRuempelung { get; set; }
        public Nullable<System.DateTime> datEinpacken { get; set; }
        public Nullable<System.DateTime> datAuspacken { get; set; }
        public Nullable<int> AufzugA { get; set; }
        public Nullable<int> AufzugB { get; set; }
        public Nullable<int> HVZA { get; set; }
        public Nullable<int> HVZB { get; set; }
        public Nullable<int> StockwerkeA { get; set; }
        public Nullable<int> StockwerkeB { get; set; }
        public Nullable<int> LaufmeterA { get; set; }
        public Nullable<int> LaufmeterB { get; set; }
        public Nullable<int> Einpacken { get; set; }
        public Nullable<int> Auspacken { get; set; }
        public Nullable<int> PackerZahl { get; set; }
        public Nullable<int> Kartons { get; set; }
        public Nullable<int> Kleiderkisten { get; set; }
        public Nullable<int> Mann { get; set; }
        public Nullable<int> Stunden { get; set; }
        public Nullable<int> SchilderBool { get; set; }
        public Nullable<System.DateTime> SchilderZeit { get; set; }
        public Nullable<int> KuecheAb { get; set; }
        public Nullable<int> KuecheAuf { get; set; }
        public Nullable<int> KuecheBau { get; set; }
        public Nullable<int> KuechePausch { get; set; }
        public Nullable<int> UmzugsDauer { get; set; }
        public string Autos { get; set; }
        public string StraßeA { get; set; }
        public string HausnummerA { get; set; }
        public Nullable<int> PLZA { get; set; }
        public string OrtA { get; set; }
        public string LandA { get; set; }
        public string StraßeB { get; set; }
        public string HausnummerB { get; set; }
        public Nullable<int> PLZB { get; set; }
        public string OrtB { get; set; }
        public string LandB { get; set; }
        public string NotizBuero { get; set; }
        public string NotizFahrer { get; set; }
        public string UserChanged { get; set; }
        public Nullable<System.DateTime> Erstelldatum { get; set; }
        public Nullable<int> PackerStunden { get; set; }
        public Nullable<int> StatUmz { get; set; }
        public Nullable<int> StatBes { get; set; }
        public Nullable<int> StatAus { get; set; }
        public Nullable<int> StatEin { get; set; }
        public Nullable<int> StatEnt { get; set; }
        public Nullable<System.TimeSpan> umzugsZeit { get; set; }
        public string HausTypA { get; set; }
        public string HausTypB { get; set; }
        public Nullable<int> AussenAufzugA { get; set; }
        public Nullable<int> AussenAufzugB { get; set; }
        public string BemerkungTitel { get; set; }
    
        public virtual Kunden Kunden { get; set; }
        public virtual ICollection<Transaktionen> Transaktionens { get; set; }
    }
}
